graph LR
  %% Memory Layer (System of Record / Reference Data)

  bc_002["💾 Settlement Instructions Management"]
  style bc_002 fill:#3498db,stroke:#333,stroke-width:2px,color:#fff
  bc_004["💾 Clearing System Directory"]
  style bc_004 fill:#3498db,stroke:#333,stroke-width:2px,color:#fff

  bc_004 --> bc_002